--------------------------------------------------------
--  File created - niedziela-czerwca-16-2019   
--------------------------------------------------------
DROP TYPE "BAZA"."FULL_NAME";
DROP TABLE "BAZA"."BIURAAGENCJI" cascade constraints;
DROP TABLE "BAZA"."FIRMY" cascade constraints;
DROP TABLE "BAZA"."KONTRAHENCI" cascade constraints;
DROP TABLE "BAZA"."KWALIFIKACJE" cascade constraints;
DROP TABLE "BAZA"."KWALIFIKACJE_KONTRAHENTOW" cascade constraints;
DROP TABLE "BAZA"."OFERTY" cascade constraints;
DROP TABLE "BAZA"."OFERTY_KWALIFIKACJE" cascade constraints;
DROP TABLE "BAZA"."STANOWISKA" cascade constraints;
DROP TABLE "BAZA"."STATUSY" cascade constraints;
DROP TABLE "BAZA"."UMOWY" cascade constraints;
DROP SEQUENCE "BAZA"."BIURAAGENCJI_SEQ";
DROP SEQUENCE "BAZA"."FIRMY_SEQ";
DROP SEQUENCE "BAZA"."KONTRAHENCI_SEQ";
DROP SEQUENCE "BAZA"."KWALIFIKACJE_SEQ";
DROP SEQUENCE "BAZA"."OFERTY_SEQ";
DROP SEQUENCE "BAZA"."STANOWISKA_SEQ";
DROP SEQUENCE "BAZA"."STATUSY_SEQ";
DROP SEQUENCE "BAZA"."UMOWY_SEQ";
DROP PROCEDURE "BAZA"."CREATE_BIUROAGENCJI";
DROP PROCEDURE "BAZA"."CREATE_FIRMA";
DROP PROCEDURE "BAZA"."CREATE_FIRMA0";
DROP PROCEDURE "BAZA"."CREATE_FIRMA1";
DROP PROCEDURE "BAZA"."CREATE_KONTRAHENT";
DROP PROCEDURE "BAZA"."CREATE_KONTRAHENT0";
DROP PROCEDURE "BAZA"."CREATE_KONTRAHENT1";
DROP PROCEDURE "BAZA"."CREATE_KWALIFIKACJA";
DROP PROCEDURE "BAZA"."CREATE_KWALIFIKACJA_KONTRAHENT";
DROP PROCEDURE "BAZA"."CREATE_KWALIFIKACJA_OFERTY";
DROP PROCEDURE "BAZA"."CREATE_OFERTA";
DROP PROCEDURE "BAZA"."CREATE_OFERTA0";
DROP PROCEDURE "BAZA"."CREATE_OFERTA1";
DROP PROCEDURE "BAZA"."CREATE_STANOWISKO";
DROP PROCEDURE "BAZA"."CREATE_STATUS";
DROP PROCEDURE "BAZA"."CREATE_UMOWA";
DROP PROCEDURE "BAZA"."CREATE_UMOWA0";
DROP PROCEDURE "BAZA"."CREATE_UMOWA1";
DROP PROCEDURE "BAZA"."GET_FIRMAF";
DROP PROCEDURE "BAZA"."GET_KONTRAHENT";
DROP PROCEDURE "BAZA"."GET_OFERTA";
DROP PROCEDURE "BAZA"."SELECT_KONTRAHENT";
DROP PROCEDURE "BAZA"."UPDATE_BIUROAGENCJI";
DROP PROCEDURE "BAZA"."UPDATE_KONTRAHENT";
DROP PROCEDURE "BAZA"."UPDATE_OFERTY";
DROP PACKAGE BODY "BAZA"."CONTRACTS";
DROP PACKAGE BODY "BAZA"."OFERTS";
DROP PACKAGE BODY "BAZA"."STATUSES";
DROP PACKAGE "BAZA"."CONTRACTS";
DROP PACKAGE "BAZA"."OFERTS";
DROP PACKAGE "BAZA"."SHOW";
DROP PACKAGE "BAZA"."STATUSES";
DROP FUNCTION "BAZA"."CONTRACTS_BETWEEN";
DROP FUNCTION "BAZA"."CONTRACTS_FROM";
--------------------------------------------------------
--  DDL for Type FULL_NAME
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "BAZA"."FULL_NAME" 
as object(
F_imie varchar(25),
F_nazw varchar(25),
Initials Varchar(7),
Member function name_full return Varchar2,
PRAGMA RESTRICT_REFERENCES(name_full,WNDS,RNDS,WNPS,RNPS));
/
CREATE OR REPLACE NONEDITIONABLE TYPE BODY "BAZA"."FULL_NAME" AS
MEMBER FUNCTION name_full return varchar2 is
BEGIN
return (F_imie || ' ' || F_nazw);
end name_full;
END;

/
--------------------------------------------------------
--  DDL for Table BIURAAGENCJI
--------------------------------------------------------

  CREATE TABLE "BAZA"."BIURAAGENCJI" 
   (	"ID_BIURA" NUMBER(10,0), 
	"MIEJSCOWOSC" VARCHAR2(30 BYTE), 
	"ULICA" VARCHAR2(30 BYTE), 
	"NR_BUDYNKU" NUMBER(6,0), 
	"NR_LOKALU" NUMBER(6,0), 
	"KOD_POCZTOWY" VARCHAR2(5 BYTE), 
	"POCZTA" VARCHAR2(30 BYTE), 
	"WOJEWODZTWO" VARCHAR2(30 BYTE), 
	"E_MAIL" VARCHAR2(50 BYTE), 
	"NR_TEL" NUMBER(12,0), 
	"FAX" NUMBER(12,0), 
	"DODANO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BAZA"."BIURAAGENCJI"."POCZTA" IS 'miejscowosc';
--------------------------------------------------------
--  DDL for Table FIRMY
--------------------------------------------------------

  CREATE TABLE "BAZA"."FIRMY" 
   (	"ID_FIRMY" NUMBER(10,0), 
	"NAZWA" VARCHAR2(30 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(30 BYTE), 
	"ULICA" VARCHAR2(30 BYTE), 
	"NR_BUDYNKU" NUMBER(6,0), 
	"NR_LOKALU" NUMBER(6,0), 
	"KOD_POCZTOWY" NUMBER(5,0), 
	"POCZTA" VARCHAR2(30 BYTE), 
	"WOJEWODZTWO" VARCHAR2(30 BYTE), 
	"E_MAIL" VARCHAR2(50 BYTE), 
	"NR_TEL" NUMBER(12,0), 
	"FAX" NUMBER(12,0), 
	"NIP" NUMBER(9,0), 
	"DODANO" DATE, 
	"ID_BIURA" NUMBER(10,0), 
	"ID_STATUS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KONTRAHENCI
--------------------------------------------------------

  CREATE TABLE "BAZA"."KONTRAHENCI" 
   (	"ID_KONTRAHENTA" NUMBER(10,0), 
	"IMIE" VARCHAR2(30 BYTE), 
	"NAZWISKO" VARCHAR2(30 BYTE), 
	"PESEL" NUMBER(11,0), 
	"PLEC" CHAR(1 BYTE), 
	"DATA_URODZENIA" DATE, 
	"MIEJSCE_URODZENIA" VARCHAR2(30 BYTE), 
	"MIEJSCOWOSC" VARCHAR2(30 BYTE), 
	"ULICA" VARCHAR2(30 BYTE), 
	"NR_BUDYNKU" NUMBER(6,0), 
	"NR_LOKALU" NUMBER(6,0), 
	"KOD_POCZTOWY" NUMBER(5,0), 
	"POCZTA" VARCHAR2(30 BYTE), 
	"WOJEWODZTWO" VARCHAR2(30 BYTE), 
	"NIP" NUMBER(9,0), 
	"NR_KONTA" VARCHAR2(28 BYTE), 
	"E_MAIL" VARCHAR2(50 BYTE), 
	"NR_TEL" NUMBER(12,0), 
	"CV" CHAR(1 BYTE), 
	"DODANO" DATE, 
	"ID_BIURA" NUMBER(10,0), 
	"ID_STATUS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BAZA"."KONTRAHENCI"."MIEJSCOWOSC" IS 'zamieszkanie';
   COMMENT ON COLUMN "BAZA"."KONTRAHENCI"."ULICA" IS 'zamieszkanie';
   COMMENT ON COLUMN "BAZA"."KONTRAHENCI"."NR_BUDYNKU" IS 'zamieszkanie';
   COMMENT ON COLUMN "BAZA"."KONTRAHENCI"."NR_LOKALU" IS 'zamieszkanie';
   COMMENT ON COLUMN "BAZA"."KONTRAHENCI"."POCZTA" IS 'miejscowosz';
--------------------------------------------------------
--  DDL for Table KWALIFIKACJE
--------------------------------------------------------

  CREATE TABLE "BAZA"."KWALIFIKACJE" 
   (	"ID_KWALIFIKACJI" NUMBER(10,0), 
	"NAZWA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KWALIFIKACJE_KONTRAHENTOW
--------------------------------------------------------

  CREATE TABLE "BAZA"."KWALIFIKACJE_KONTRAHENTOW" 
   (	"ID_KONTRAHENTA" NUMBER(10,0), 
	"ID_KWALIFIKACJI" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OFERTY
--------------------------------------------------------

  CREATE TABLE "BAZA"."OFERTY" 
   (	"ID_OFERTY" NUMBER(10,0), 
	"WYMIAR_PRACY" VARCHAR2(10 BYTE), 
	"STAWKA_DZIEN" FLOAT(5), 
	"STAWKA_NOC" FLOAT(5), 
	"STAWKA_ND_SW" FLOAT(5), 
	"ILOSC_OFERT" NUMBER(4,0), 
	"OPIS" VARCHAR2(4000 BYTE), 
	"DODANO" DATE, 
	"ID_STANOWISKA" NUMBER(10,0), 
	"ID_FIRMY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OFERTY_KWALIFIKACJE
--------------------------------------------------------

  CREATE TABLE "BAZA"."OFERTY_KWALIFIKACJE" 
   (	"ID_OFERTY" NUMBER(10,0), 
	"ID_KWALIFIKACJI" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STANOWISKA
--------------------------------------------------------

  CREATE TABLE "BAZA"."STANOWISKA" 
   (	"ID_STANOWISKA" NUMBER(10,0), 
	"NAZWA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATUSY
--------------------------------------------------------

  CREATE TABLE "BAZA"."STATUSY" 
   (	"ID_STATUSU" NUMBER(10,0), 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UMOWY
--------------------------------------------------------

  CREATE TABLE "BAZA"."UMOWY" 
   (	"ID_UMOWY" NUMBER(10,0), 
	"POCZATEK" DATE, 
	"KONIEC" DATE, 
	"RODZAJ" VARCHAR2(20 BYTE), 
	"DODANO" DATE, 
	"ID_OFERTY" NUMBER(10,0), 
	"ID_KONTRAHENTA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence BIURAAGENCJI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."BIURAAGENCJI_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FIRMY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."FIRMY_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence KONTRAHENCI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."KONTRAHENCI_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence KWALIFIKACJE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."KWALIFIKACJE_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence OFERTY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."OFERTY_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STANOWISKA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."STANOWISKA_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence STATUSY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."STATUSY_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence UMOWY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BAZA"."UMOWY_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
REM INSERTING into BAZA.BIURAAGENCJI
SET DEFINE OFF;
Insert into BAZA.BIURAAGENCJI (ID_BIURA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,E_MAIL,NR_TEL,FAX,DODANO) values ('1','Olsztyn','Jana Pawla 2','5','3','-100','Olsztyn','Inne','olsztyn@hrstudio.pl','48605505405','11456321789',to_date('19/01/01','RR/MM/DD'));
REM INSERTING into BAZA.FIRMY
SET DEFINE OFF;
Insert into BAZA.FIRMY (ID_FIRMY,NAZWA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,E_MAIL,NR_TEL,FAX,NIP,DODANO,ID_BIURA,ID_STATUS) values ('1','Workforce','Inna','Armii Krajowej','6','5','30300','Inna','Opolskie','job@workforce.pl','555555555','555555555','700800900',to_date('19/02/28','RR/MM/DD'),'1','4');
Insert into BAZA.FIRMY (ID_FIRMY,NAZWA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,E_MAIL,NR_TEL,FAX,NIP,DODANO,ID_BIURA,ID_STATUS) values ('21','Otto','Amsterdam','Nationale','5','12','45678','Amsterdam',null,'otto@workforce.com','123456789','123456789','753951468',to_date('19/06/16','RR/MM/DD'),'1','4');
REM INSERTING into BAZA.KONTRAHENCI
SET DEFINE OFF;
Insert into BAZA.KONTRAHENCI (ID_KONTRAHENTA,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,MIEJSCE_URODZENIA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,NIP,NR_KONTA,E_MAIL,NR_TEL,CV,DODANO,ID_BIURA,ID_STATUS) values ('21','Andrzej','Konstantynopolitańczykiewicz','55101503215','M',to_date('55/10/15','RR/MM/DD'),'Sieradz','Zielecin','Długa','107','143','50500','Sieradz','Łódzkie','900800700','PL68253418950123795000000490','e@malia.pl','48754238454','T',to_date('19/03/01','RR/MM/DD'),'1','1');
Insert into BAZA.KONTRAHENCI (ID_KONTRAHENTA,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,MIEJSCE_URODZENIA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,NIP,NR_KONTA,E_MAIL,NR_TEL,CV,DODANO,ID_BIURA,ID_STATUS) values ('42','Marlena','Kupga','920229','K',to_date('92/02/28','RR/MM/DD'),'Opole','Opole','DÅ‚uga','79','2','55100','Opole','Opolskie',null,'PL74185209631477411477666222','mail@e.pl','48654789222','T',to_date('19/06/16','RR/MM/DD'),'1','1');
Insert into BAZA.KONTRAHENCI (ID_KONTRAHENTA,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,MIEJSCE_URODZENIA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,NIP,NR_KONTA,E_MAIL,NR_TEL,CV,DODANO,ID_BIURA,ID_STATUS) values ('41','Janusz','Nowak','74112045678','M',to_date('74/10/20','RR/MM/DD'),'Warszawa','Olsztyn','Naftowa','12','20','77500',null,null,null,'PL88000064795523147900000006','mail@mail.mail','48505606404','T',to_date('19/06/16','RR/MM/DD'),'1','3');
Insert into BAZA.KONTRAHENCI (ID_KONTRAHENTA,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,MIEJSCE_URODZENIA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,NIP,NR_KONTA,E_MAIL,NR_TEL,CV,DODANO,ID_BIURA,ID_STATUS) values ('44','Aleksandra','Wolska','860525','K',to_date('86/05/25','RR/MM/DD'),'ÅÃ³dÅº','ÅÃ³dÅº','Kwiatowa','4',null,'78440','ÅÃ³dÅº','ÅÃ³dzkie',null,'PL6664850134444895317000001','google@gmail.com','48600555485','N',to_date('19/06/16','RR/MM/DD'),'1','3');
Insert into BAZA.KONTRAHENCI (ID_KONTRAHENTA,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,MIEJSCE_URODZENIA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,NIP,NR_KONTA,E_MAIL,NR_TEL,CV,DODANO,ID_BIURA,ID_STATUS) values ('47','Wojciech','Gazda','881215','M',to_date('88/12/15','RR/MM/DD'),'Krosno','Krosno','TysiÄ…clecia','26','45','38440','Korsno','Podkarpackie',null,'PL746485219700001674000022','firma@wlasna.pl','48605405505','T',to_date('19/06/16','RR/MM/DD'),'1','1');
Insert into BAZA.KONTRAHENCI (ID_KONTRAHENTA,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,MIEJSCE_URODZENIA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,NIP,NR_KONTA,E_MAIL,NR_TEL,CV,DODANO,ID_BIURA,ID_STATUS) values ('81','Andrzej','Kowalski','55033036547','M',to_date('55/03/30','RR/MM/DD'),'WieluÅ„','WieluÅ„','Kwiatowa','66',null,'66444','WieluÅ„','Inne',null,'PL33256664782221564892200134','mail@e.com','48654654654','T',to_date('19/06/17','RR/MM/DD'),'1','1');
Insert into BAZA.KONTRAHENCI (ID_KONTRAHENTA,IMIE,NAZWISKO,PESEL,PLEC,DATA_URODZENIA,MIEJSCE_URODZENIA,MIEJSCOWOSC,ULICA,NR_BUDYNKU,NR_LOKALU,KOD_POCZTOWY,POCZTA,WOJEWODZTWO,NIP,NR_KONTA,E_MAIL,NR_TEL,CV,DODANO,ID_BIURA,ID_STATUS) values ('82','Marlena','Kupaga','63052265987','K',to_date('63/05/22','RR/MM/DD'),'Oborniki','Oborniki','Zielona','111',null,'33300','Oborniki','TAK','987654321','PL54862333180000004765220001','mail@serwis.pl','48123456789','N',to_date('19/06/17','RR/MM/DD'),'1','3');
REM INSERTING into BAZA.KWALIFIKACJE
SET DEFINE OFF;
Insert into BAZA.KWALIFIKACJE (ID_KWALIFIKACJI,NAZWA) values ('1','Język Angielski');
Insert into BAZA.KWALIFIKACJE (ID_KWALIFIKACJI,NAZWA) values ('2','Język Niemiecki');
Insert into BAZA.KWALIFIKACJE (ID_KWALIFIKACJI,NAZWA) values ('3','Język Rosyjski');
Insert into BAZA.KWALIFIKACJE (ID_KWALIFIKACJI,NAZWA) values ('4','Język Włoski');
Insert into BAZA.KWALIFIKACJE (ID_KWALIFIKACJI,NAZWA) values ('5','Język Japoński');
Insert into BAZA.KWALIFIKACJE (ID_KWALIFIKACJI,NAZWA) values ('6','Język Hiszpański');
Insert into BAZA.KWALIFIKACJE (ID_KWALIFIKACJI,NAZWA) values ('21','Spawacz');
REM INSERTING into BAZA.KWALIFIKACJE_KONTRAHENTOW
SET DEFINE OFF;
REM INSERTING into BAZA.OFERTY
SET DEFINE OFF;
Insert into BAZA.OFERTY (ID_OFERTY,WYMIAR_PRACY,STAWKA_DZIEN,STAWKA_NOC,STAWKA_ND_SW,ILOSC_OFERT,OPIS,DODANO,ID_STANOWISKA,ID_FIRMY) values ('1','Pełny','15','19','20','5','praca',to_date('19/03/15','RR/MM/DD'),'2','1');
Insert into BAZA.OFERTY (ID_OFERTY,WYMIAR_PRACY,STAWKA_DZIEN,STAWKA_NOC,STAWKA_ND_SW,ILOSC_OFERT,OPIS,DODANO,ID_STANOWISKA,ID_FIRMY) values ('21','2/3','13','15','16','11','Oferta XYZ',to_date('19/06/17','RR/MM/DD'),'5','21');
REM INSERTING into BAZA.OFERTY_KWALIFIKACJE
SET DEFINE OFF;
REM INSERTING into BAZA.STANOWISKA
SET DEFINE OFF;
Insert into BAZA.STANOWISKA (ID_STANOWISKA,NAZWA) values ('1','Kierownik');
Insert into BAZA.STANOWISKA (ID_STANOWISKA,NAZWA) values ('2','Brygadzista');
Insert into BAZA.STANOWISKA (ID_STANOWISKA,NAZWA) values ('3','Pracownik');
Insert into BAZA.STANOWISKA (ID_STANOWISKA,NAZWA) values ('4','Kasjer');
Insert into BAZA.STANOWISKA (ID_STANOWISKA,NAZWA) values ('5','Magazynier');
Insert into BAZA.STANOWISKA (ID_STANOWISKA,NAZWA) values ('6','Sprzedawca');
Insert into BAZA.STANOWISKA (ID_STANOWISKA,NAZWA) values ('21','Pomocnik');
REM INSERTING into BAZA.STATUSY
SET DEFINE OFF;
Insert into BAZA.STATUSY (ID_STATUSU,STATUS) values ('1','Zatrudniony');
Insert into BAZA.STATUSY (ID_STATUSU,STATUS) values ('2','Oczekujący');
Insert into BAZA.STATUSY (ID_STATUSU,STATUS) values ('3','Zarejestrowany');
Insert into BAZA.STATUSY (ID_STATUSU,STATUS) values ('4','Rekrutacja');
Insert into BAZA.STATUSY (ID_STATUSU,STATUS) values ('21','Zwolniony');
REM INSERTING into BAZA.UMOWY
SET DEFINE OFF;
Insert into BAZA.UMOWY (ID_UMOWY,POCZATEK,KONIEC,RODZAJ,DODANO,ID_OFERTY,ID_KONTRAHENTA) values ('3',to_date('03/05/03','RR/MM/DD'),to_date('03/05/03','RR/MM/DD'),'tymczasowa',to_date('03/05/03','RR/MM/DD'),null,null);
Insert into BAZA.UMOWY (ID_UMOWY,POCZATEK,KONIEC,RODZAJ,DODANO,ID_OFERTY,ID_KONTRAHENTA) values ('24',to_date('19/06/01','RR/MM/DD'),to_date('19/07/01','RR/MM/DD'),'tymczasowa',to_date('19/05/25','RR/MM/DD'),'1','21');
--------------------------------------------------------
--  DDL for Index BIURAAGENCJI_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."BIURAAGENCJI_INDEX1" ON "BAZA"."BIURAAGENCJI" ("ID_BIURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FIRMY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."FIRMY_PK" ON "BAZA"."FIRMY" ("ID_FIRMY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KONTRACHENCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."KONTRACHENCI_PK" ON "BAZA"."KONTRAHENCI" ("ID_KONTRAHENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KONTRAHENCI_PESEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."KONTRAHENCI_PESEL" ON "BAZA"."KONTRAHENCI" ("PESEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KWALIFIKACJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."KWALIFIKACJE_PK" ON "BAZA"."KWALIFIKACJE" ("ID_KWALIFIKACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OFERTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."OFERTY_PK" ON "BAZA"."OFERTY" ("ID_OFERTY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STANOWISKA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."STANOWISKA_PK" ON "BAZA"."STANOWISKA" ("ID_STANOWISKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STATUSY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."STATUSY_PK" ON "BAZA"."STATUSY" ("ID_STATUSU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UMOWY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BAZA"."UMOWY_PK" ON "BAZA"."UMOWY" ("ID_UMOWY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CREATE_BIUROAGENCJI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_BIUROAGENCJI" 
BEFORE INSERT ON BIURAAGENCJI 
FOR EACH ROW
BEGIN
  :new.ID_BIURA:=BIURAAGENCJI_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BAZA"."CREATE_BIUROAGENCJI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREATE_FIRMA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_FIRMA" 
BEFORE INSERT ON FIRMY 
FOR EACH ROW
BEGIN
  :new.ID_FIRMY:=FIRMY_SEQ.nextval;
END;
/
ALTER TRIGGER "BAZA"."CREATE_FIRMA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREATE_KONTRAHENT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_KONTRAHENT" 
BEFORE INSERT ON KONTRAHENCI 
FOR EACH ROW
BEGIN
  :new.ID_KONTRAHENTA:=KONTRAHENCI_SEQ.nextval;
END;
/
ALTER TRIGGER "BAZA"."CREATE_KONTRAHENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREATE_KWALIFIKACJA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_KWALIFIKACJA" 
BEFORE INSERT ON KWALIFIKACJE 
FOR EACH ROW
BEGIN
  :new.ID_KWALIFIKACJI:=KWALIFIKACJE_SEQ.nextval;
END;
/
ALTER TRIGGER "BAZA"."CREATE_KWALIFIKACJA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREATE_OFERTA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_OFERTA" 
BEFORE INSERT ON OFERTY 
FOR EACH ROW
BEGIN
  :new.ID_OFERTY:=OFERTY_SEQ.nextval;
END;
/
ALTER TRIGGER "BAZA"."CREATE_OFERTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREATE_STANOWISKO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_STANOWISKO" 
BEFORE INSERT ON STANOWISKA 
FOR EACH ROW
BEGIN
  :new.ID_STANOWISKA:=STANOWISKA_SEQ.nextval;
END;
/
ALTER TRIGGER "BAZA"."CREATE_STANOWISKO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREATE_STATUS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_STATUS" 
BEFORE INSERT ON STATUSY 
FOR EACH ROW
BEGIN
  :new.ID_STATUSU:=STATUSY_SEQ.nextval;
END;
/
ALTER TRIGGER "BAZA"."CREATE_STATUS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CREATE_UMOWA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "BAZA"."CREATE_UMOWA" 
BEFORE INSERT ON UMOWY 
FOR EACH ROW
BEGIN
  :new.ID_UMOWY:=UMOWY_SEQ.NEXTVAL;
END;
/
ALTER TRIGGER "BAZA"."CREATE_UMOWA" ENABLE;
--------------------------------------------------------
--  DDL for Procedure CREATE_BIUROAGENCJI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_BIUROAGENCJI" 
(
  BIURO_MIEJSCOWOSC IN VARCHAR2 
, BIURO_ULICA IN VARCHAR2 
, BIURO_NR_BUDYNKU IN NUMBER 
, BIURO_NR_LOKALU IN NUMBER
, BIURO_KOD_POCZTOWY IN VARCHAR2 
, BIURO_POCZTA IN VARCHAR2 
, BIURO_WOJEWODZTWO IN VARCHAR2 
, BIURO_E_MAIL IN VARCHAR2 
, BIURO_NR_TEL IN NUMBER 
, BIURO_FAX IN NUMBER 
, BIURO_DODANO IN DATE
) AS 
BEGIN
  INSERT INTO BIURAAGENCJI(
  MIEJSCOWOSC
, ULICA 
, NR_BUDYNKU
, NR_LOKALU 
, KOD_POCZTOWY
, POCZTA 
, WOJEWODZTWO 
, E_MAIL 
, NR_TEL 
, FAX 
, DODANO 
  )VALUES(
  BIURO_MIEJSCOWOSC 
, BIURO_ULICA 
, BIURO_NR_BUDYNKU 
, BIURO_NR_LOKALU 
, BIURO_KOD_POCZTOWY 
, BIURO_POCZTA 
, BIURO_WOJEWODZTWO 
, BIURO_E_MAIL 
, BIURO_NR_TEL 
, BIURO_FAX 
, BIURO_DODANO);
END CREATE_BIUROAGENCJI;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_FIRMA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_FIRMA" 
(
  FIRMA_NAZWA IN VARCHAR2 
, FIRMA_MIEJSCOWOSC IN VARCHAR2 
, FIRMA_ULICA IN VARCHAR2 
, FIRMA_NR_BUDYNKU IN NUMBER 
, FIRMA_NR_LOKALU IN NUMBER
, FIRMA_KOD_POCZTOWY IN NUMBER 
, FIRMA_POCZTA IN VARCHAR2 
, FIRMA_WOJEWODZTWO IN VARCHAR2 
, FIRMA_E_MAIL IN VARCHAR2 
, FIRMA_NR_TEL IN NUMBER 
, FIRMA_FAX IN NUMBER 
, FIRMA_NIP IN NUMBER 
, FIRMA_DODANO IN DATE
) AS 
BEGIN
  INSERT INTO FIRMY(
  NAZWA 
, MIEJSCOWOSC 
, ULICA 
, NR_BUDYNKU 
, NR_LOKALU 
, KOD_POCZTOWY 
, POCZTA 
, WOJEWODZTWO 
, E_MAIL 
, NR_TEL 
, FAX 
, NIP 
, DODANO
  )VALUES(
  FIRMA_NAZWA 
, FIRMA_MIEJSCOWOSC 
, FIRMA_ULICA 
, FIRMA_NR_BUDYNKU 
, FIRMA_NR_LOKALU 
, FIRMA_KOD_POCZTOWY 
, FIRMA_POCZTA 
, FIRMA_WOJEWODZTWO 
, FIRMA_E_MAIL 
, FIRMA_NR_TEL 
, FIRMA_FAX 
, FIRMA_NIP 
, FIRMA_DODANO
);
END CREATE_FIRMA;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_FIRMA0
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_FIRMA0" 
(
  FIRMA_NAZWA IN VARCHAR2 
, FIRMA_MIEJSCOWOSC IN VARCHAR2 
, FIRMA_ULICA IN VARCHAR2 
, FIRMA_NR_BUDYNKU IN NUMBER 
, FIRMA_NR_LOKALU IN NUMBER
, FIRMA_KOD_POCZTOWY IN NUMBER 
, FIRMA_POCZTA IN VARCHAR2 
, FIRMA_WOJEWODZTWO IN VARCHAR2 
, FIRMA_E_MAIL IN VARCHAR2 
, FIRMA_NR_TEL IN NUMBER 
, FIRMA_FAX IN NUMBER 
, FIRMA_NIP IN NUMBER 
, FIRMA_DODANO IN DATE
,	FIRMA_ID_BIURA IN NUMBER
, FIRMA_ID_STATUS IN NUMBER
) AS 
BEGIN
  INSERT INTO FIRMY(
  NAZWA 
, MIEJSCOWOSC 
, ULICA 
, NR_BUDYNKU 
, NR_LOKALU 
, KOD_POCZTOWY 
, POCZTA 
, WOJEWODZTWO 
, E_MAIL 
, NR_TEL 
, FAX 
, NIP 
, DODANO
, ID_BIURA
, ID_STATUS
  )VALUES(
  FIRMA_NAZWA 
, FIRMA_MIEJSCOWOSC 
, FIRMA_ULICA 
, FIRMA_NR_BUDYNKU 
, FIRMA_NR_LOKALU 
, FIRMA_KOD_POCZTOWY 
, FIRMA_POCZTA 
, FIRMA_WOJEWODZTWO 
, FIRMA_E_MAIL 
, FIRMA_NR_TEL 
, FIRMA_FAX 
, FIRMA_NIP 
, FIRMA_DODANO
, FIRMA_ID_BIURA 
, FIRMA_ID_STATUS
);
END CREATE_FIRMA0;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_FIRMA1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_FIRMA1" 
(
  FIRMA_NAZWA IN VARCHAR2 
, FIRMA_MIEJSCOWOSC IN VARCHAR2 
, FIRMA_ULICA IN VARCHAR2 
, FIRMA_NR_BUDYNKU IN NUMBER 
, FIRMA_NR_LOKALU IN NUMBER
, FIRMA_KOD_POCZTOWY IN NUMBER 
, FIRMA_POCZTA IN VARCHAR2 
, FIRMA_WOJEWODZTWO IN VARCHAR2 
, FIRMA_E_MAIL IN VARCHAR2 
, FIRMA_NR_TEL IN NUMBER 
, FIRMA_FAX IN NUMBER 
, FIRMA_NIP IN NUMBER 
, FIRMA_DODANO IN DATE
,	MIEJSCOWOSC IN VARCHAR2
, ULICA IN VARCHAR2
, BUDYNEK IN NUMBER
, STATUS IN VARCHAR2
) AS 
BEGIN
  INSERT INTO FIRMY(
  NAZWA 
, MIEJSCOWOSC 
, ULICA 
, NR_BUDYNKU 
, NR_LOKALU 
, KOD_POCZTOWY 
, POCZTA 
, WOJEWODZTWO 
, E_MAIL 
, NR_TEL 
, FAX 
, NIP 
, DODANO
, ID_BIURA
, ID_STATUS
  )VALUES(
  FIRMA_NAZWA 
, FIRMA_MIEJSCOWOSC 
, FIRMA_ULICA 
, FIRMA_NR_BUDYNKU 
, FIRMA_NR_LOKALU 
, FIRMA_KOD_POCZTOWY 
, FIRMA_POCZTA 
, FIRMA_WOJEWODZTWO 
, FIRMA_E_MAIL 
, FIRMA_NR_TEL 
, FIRMA_FAX 
, FIRMA_NIP 
, FIRMA_DODANO
, (SELECT b.ID_BIURA FROM BIURAAGENCJI b WHERE b.MIEJSCOWOSC=MIEJSCOWOSC AND b.ULICA=ULICA AND b.NR_BUDYNKU=BUDYNEK)
, (SELECT s.ID_STATUSU FROM STATUSY s WHERE s.STATUS=STATUS)
);
END CREATE_FIRMA1;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_KONTRAHENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_KONTRAHENT" 
(
  KONTRAHENT_IMIE IN VARCHAR2 
, KONTRAHENT_NAZWISKO IN VARCHAR2 
, KONTRAHENT_PESEL IN NUMBER 
, KONTRAHENT_PLEC IN VARCHAR2 
, KONTRAHENT_DATA_URODZENIA IN DATE 
, KONTRAHENT_MIEJSCE_URODZENIA IN VARCHAR2 
, KONTRAHENT_MIEJSCOWOSC IN VARCHAR2 
, KONTRAHENT_ULICA IN VARCHAR2 
, KONTRAHENT_NR_BUDYNKU IN NUMBER 
, KONTRAHENT_NR_LOKALU IN NUMBER 
, KONTRAHENT_KOD_POCZTOWY IN NUMBER 
, KONTRAHENT_POCZTA IN VARCHAR2 
, KONTRAHENT_WOJEWODZTWO IN VARCHAR2 
, KONTRAHENT_NIP IN NUMBER 
, KONTRAHENT_NR_KONTA IN VARCHAR2
, KONTRAHENT_E_MAIL IN VARCHAR2 
, KONTRAHENT_NR_TEL IN NUMBER 
, KONTRAHENT_CV IN VARCHAR2 
, KONTRAHENT_DODANO IN DATE
) AS 
BEGIN
  INSERT INTO KONTRAHENCI(
  IMIE	
,  NAZWISKO	
,  PESEL	
,  PLEC	
,  DATA_URODZENIA
,  MIEJSCE_URODZENIA
,  MIEJSCOWOSC	
,  ULICA	
,  NR_BUDYNKU
,  NR_LOKALU
,  KOD_POCZTOWY
,  POCZTA
,  WOJEWODZTWO	
,  NIP	
,  NR_KONTA
,  E_MAIL
,  NR_TEL
,  CV	
,  DODANO
  )VALUES(
  KONTRAHENT_IMIE
, KONTRAHENT_NAZWISKO
, KONTRAHENT_PESEL
, KONTRAHENT_PLEC
, KONTRAHENT_DATA_URODZENIA
, KONTRAHENT_MIEJSCE_URODZENIA
, KONTRAHENT_MIEJSCOWOSC
, KONTRAHENT_ULICA
, KONTRAHENT_NR_BUDYNKU
, KONTRAHENT_NR_LOKALU
, KONTRAHENT_KOD_POCZTOWY
, KONTRAHENT_POCZTA
, KONTRAHENT_WOJEWODZTWO
, KONTRAHENT_NIP
, KONTRAHENT_NR_KONTA
, KONTRAHENT_E_MAIL
, KONTRAHENT_NR_TEL
, KONTRAHENT_CV
, KONTRAHENT_DODANO
  );
END CREATE_KONTRAHENT;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_KONTRAHENT0
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_KONTRAHENT0" 
(
  KONTRAHENT_IMIE IN VARCHAR2 
, KONTRAHENT_NAZWISKO IN VARCHAR2 
, KONTRAHENT_PESEL IN NUMBER 
, KONTRAHENT_PLEC IN VARCHAR2 
, KONTRAHENT_DATA_URODZENIA IN DATE 
, KONTRAHENT_MIEJSCE_URODZENIA IN VARCHAR2 
, KONTRAHENT_MIEJSCOWOSC IN VARCHAR2 
, KONTRAHENT_ULICA IN VARCHAR2 
, KONTRAHENT_NR_BUDYNKU IN NUMBER 
, KONTRAHENT_NR_LOKALU IN NUMBER 
, KONTRAHENT_KOD_POCZTOWY IN NUMBER 
, KONTRAHENT_POCZTA IN VARCHAR2 
, KONTRAHENT_WOJEWODZTWO IN VARCHAR2 
, KONTRAHENT_NIP IN NUMBER 
, KONTRAHENT_NR_KONTA IN VARCHAR2
, KONTRAHENT_E_MAIL IN VARCHAR2 
, KONTRAHENT_NR_TEL IN NUMBER 
, KONTRAHENT_CV IN VARCHAR2 
, KONTRAHENT_DODANO IN DATE
, KONTRAHENT_ID_BIURA IN NUMBER
, KONTRAHENT_ID_STATUS IN NUMBER
) AS 
BEGIN
  INSERT INTO KONTRAHENCI(
  IMIE	
,  NAZWISKO	
,  PESEL	
,  PLEC	
,  DATA_URODZENIA
,  MIEJSCE_URODZENIA
,  MIEJSCOWOSC	
,  ULICA	
,  NR_BUDYNKU
,  NR_LOKALU
,  KOD_POCZTOWY
,  POCZTA
,  WOJEWODZTWO	
,  NIP	
,  NR_KONTA
,  E_MAIL
,  NR_TEL
,  CV	
,  DODANO
, ID_BIURA
, ID_STATUS
  )VALUES(
  KONTRAHENT_IMIE
, KONTRAHENT_NAZWISKO
, KONTRAHENT_PESEL
, KONTRAHENT_PLEC
, KONTRAHENT_DATA_URODZENIA
, KONTRAHENT_MIEJSCE_URODZENIA
, KONTRAHENT_MIEJSCOWOSC
, KONTRAHENT_ULICA
, KONTRAHENT_NR_BUDYNKU
, KONTRAHENT_NR_LOKALU
, KONTRAHENT_KOD_POCZTOWY
, KONTRAHENT_POCZTA
, KONTRAHENT_WOJEWODZTWO
, KONTRAHENT_NIP
, KONTRAHENT_NR_KONTA
, KONTRAHENT_E_MAIL
, KONTRAHENT_NR_TEL
, KONTRAHENT_CV
, KONTRAHENT_DODANO
, KONTRAHENT_ID_BIURA
, KONTRAHENT_ID_STATUS
  );
END CREATE_KONTRAHENT0;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_KONTRAHENT1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_KONTRAHENT1" 
(
  KONTRAHENT_IMIE IN VARCHAR2 
, KONTRAHENT_NAZWISKO IN VARCHAR2 
, KONTRAHENT_PESEL IN NUMBER 
, KONTRAHENT_PLEC IN VARCHAR2 
, KONTRAHENT_DATA_URODZENIA IN DATE 
, KONTRAHENT_MIEJSCE_URODZENIA IN VARCHAR2 
, KONTRAHENT_MIEJSCOWOSC IN VARCHAR2 
, KONTRAHENT_ULICA IN VARCHAR2 
, KONTRAHENT_NR_BUDYNKU IN NUMBER 
, KONTRAHENT_NR_LOKALU IN NUMBER 
, KONTRAHENT_KOD_POCZTOWY IN NUMBER 
, KONTRAHENT_POCZTA IN VARCHAR2 
, KONTRAHENT_WOJEWODZTWO IN VARCHAR2 
, KONTRAHENT_NIP IN NUMBER 
, KONTRAHENT_NR_KONTA IN VARCHAR2
, KONTRAHENT_E_MAIL IN VARCHAR2 
, KONTRAHENT_NR_TEL IN NUMBER 
, KONTRAHENT_CV IN VARCHAR2 
, KONTRAHENT_DODANO IN DATE
, MIEJSCOWOSC IN VARCHAR2
, ULICA in VARCHAR2
, NR_BUDYNKU in NUMBER
, STATUS in VARCHAR2
) AS 
BEGIN
  INSERT INTO KONTRAHENCI(
  IMIE	
,  NAZWISKO	
,  PESEL	
,  PLEC	
,  DATA_URODZENIA
,  MIEJSCE_URODZENIA
,  MIEJSCOWOSC	
,  ULICA	
,  NR_BUDYNKU
,  NR_LOKALU
,  KOD_POCZTOWY
,  POCZTA
,  WOJEWODZTWO	
,  NIP	
,  NR_KONTA
,  E_MAIL
,  NR_TEL
,  CV	
,  DODANO
, ID_BIURA
, ID_STATUS
  )VALUES(
  KONTRAHENT_IMIE
, KONTRAHENT_NAZWISKO
, KONTRAHENT_PESEL
, KONTRAHENT_PLEC
, KONTRAHENT_DATA_URODZENIA
, KONTRAHENT_MIEJSCE_URODZENIA
, KONTRAHENT_MIEJSCOWOSC
, KONTRAHENT_ULICA
, KONTRAHENT_NR_BUDYNKU
, KONTRAHENT_NR_LOKALU
, KONTRAHENT_KOD_POCZTOWY
, KONTRAHENT_POCZTA
, KONTRAHENT_WOJEWODZTWO
, KONTRAHENT_NIP
, KONTRAHENT_NR_KONTA
, KONTRAHENT_E_MAIL
, KONTRAHENT_NR_TEL
, KONTRAHENT_CV
, KONTRAHENT_DODANO
, (SELECT b.ID_BIURA FROM BIURAAGENCJI b WHERE b.MIEJSCOWOSC=MIEJSCOWOSC AND b.ULICA=ULICA AND b.NR_BUDYNKU=NR_BUDYNKU)
, (SELECT s.ID_STATUSU FROM STATUSY s WHERE s.STATUS=STATUS)
  );
END CREATE_KONTRAHENT1;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_KWALIFIKACJA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_KWALIFIKACJA" 
(
  KWALIFIKACJA_NAZWA IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO KWALIFIKACJE(
  NAZWA)VALUES(
  KWALIFIKACJA_NAZWA);
END CREATE_KWALIFIKACJA;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_KWALIFIKACJA_KONTRAHENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_KWALIFIKACJA_KONTRAHENT" (
  kwal_nazwa IN varchar2 
, kon_nazwi IN varchar2
, kon_imie IN varchar2
, kon_tel in number
, kon_miejsce in varchar2
) AS 
BEGIN
  INSERT INTO KWALIFIKACJE_KONTRAHENTOW(
  ID_KONTRAHENTA,
  ID_KWALIFIKACJI
  )Select kwa.ID_KWALIFIKACJI, ko.ID_KONTRAHENTA from KWALIFIKACJE kwa, KONTRAHENCI ko Where kwa.nazwa=kwal_nazwa AND ko.nazwisko=kon_nazwi AND ko.imie=kon_imie AND ko.nr_tel=kon_tel AND ko.miejscowosc=kon_miejsce;
END CREATE_KWALIFIKACJA_KONTRAHENT;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_KWALIFIKACJA_OFERTY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_KWALIFIKACJA_OFERTY" 
(
  fir_nazwa IN varchar2 
, stano_nazwa IN varchar2
, kwa_nazwa IN varchar2
, ofe_wymiar in varchar2
, ofe_sta_dz in number
) AS 
BEGIN
  INSERT INTO OFERTY_KWALIFIKACJE(
  ID_OFERTY,
  ID_KWALIFIKACJI
  )SELECT o.ID_OFERTY, k.ID_KWALIFIKACJI 
  FROM OFERTY o, KWALIFIKACJE k, FIRMY f, STANOWISKA s
  WHERE k.nazwa=kwa_nazwa AND f.nazwa=fir_nazwa AND o.wymiar_pracy=ofe_wymiar AND o.stawka_dzien=ofe_sta_dz AND s.nazwa=stano_nazwa;
END CREATE_KWALIFIKACJA_OFERTY;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_OFERTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_OFERTA" 
(
  OFERTA_WYMIAR_PRACY IN VARCHAR2 
, OFERTA_STAWKA_DZIEN IN NUMBER 
, OFERTA_STAWKA_NOC IN NUMBER 
, OFERTA_STAWKA_ND_SW IN NUMBER 
, OFERTA_ILOSC_OFERT IN NUMBER 
, OFERTA_OPIS IN VARCHAR2 
, OFERTA_DODANO IN DATE 
) AS 
BEGIN
  INSERT INTO OFERTY(
  WYMIAR_PRACY
,STAWKA_DZIEN
,STAWKA_NOC
,STAWKA_ND_SW
,ILOSC_OFERT
,OPIS
,DODANO
)VALUES(
OFERTA_WYMIAR_PRACY
,OFERTA_STAWKA_DZIEN
,OFERTA_STAWKA_NOC
,OFERTA_STAWKA_ND_SW
,OFERTA_ILOSC_OFERT
,OFERTA_OPIS
,OFERTA_DODANO
);
END CREATE_OFERTA;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_OFERTA0
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_OFERTA0" 
(
  OFERTA_WYMIAR_PRACY IN VARCHAR2 
, OFERTA_STAWKA_DZIEN IN NUMBER 
, OFERTA_STAWKA_NOC IN NUMBER
, OFERTA_STAWKA_ND_SW IN NUMBER
, OFERTA_ILOSC_OFERT IN NUMBER 
, OFERTA_OPIS IN VARCHAR2 
, OFERTA_DODANO IN DATE
, OFERTA_ID_STANOWISKA IN NUMBER
, OFERTA_ID_FIRMY IN NUMBER
) AS 
BEGIN
  INSERT INTO OFERTY(
  WYMIAR_PRACY
,STAWKA_DZIEN
,STAWKA_NOC
,STAWKA_ND_SW
,ILOSC_OFERT
,OPIS
,DODANO
,ID_STANOWISKA
,ID_FIRMY
)VALUES(
OFERTA_WYMIAR_PRACY
,OFERTA_STAWKA_DZIEN
,OFERTA_STAWKA_NOC
,OFERTA_STAWKA_ND_SW
,OFERTA_ILOSC_OFERT
,OFERTA_OPIS
,OFERTA_DODANO
,OFERTA_ID_STANOWISKA
, OFERTA_ID_FIRMY
);
END CREATE_OFERTA0;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_OFERTA1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_OFERTA1" 
(
  OFERTA_WYMIAR_PRACY IN VARCHAR2 
, OFERTA_STAWKA_DZIEN IN NUMBER 
, OFERTA_STAWKA_NOC IN NUMBER 
, OFERTA_STAWKA_ND_SW IN NUMBER 
, OFERTA_ILOSC_OFERT IN NUMBER 
, OFERTA_OPIS IN VARCHAR2 
, OFERTA_DODANO IN DATE
, STANOWISKO IN VARCHAR2
, NAZWA IN VARCHAR2
) AS 
BEGIN
  INSERT INTO OFERTY(
  WYMIAR_PRACY
,STAWKA_DZIEN
,STAWKA_NOC
,STAWKA_ND_SW
,ILOSC_OFERT
,OPIS
,DODANO
,ID_STANOWISKA
,ID_FIRMY
)VALUES(
OFERTA_WYMIAR_PRACY
,OFERTA_STAWKA_DZIEN
,OFERTA_STAWKA_NOC
,OFERTA_STAWKA_ND_SW
,OFERTA_ILOSC_OFERT
,OFERTA_OPIS
,OFERTA_DODANO
,(SELECT s.ID_STANOWISKA FROM STANOWISKA s WHERE s.NAZWA=STANOWISKO)
,(SELECT f.ID_FIRMY FROM FIRMY f WHERE f.NAZWA=NAZWA)
);
END CREATE_OFERTA1;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_STANOWISKO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_STANOWISKO" 
(
  STANOWISKO_NAZWA IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO STANOWISKA(NAZWA)VALUES(STANOWISKO_NAZWA);
END CREATE_STANOWISKO;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_STATUS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_STATUS" 
(
  STATUS_NAZWA IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO STATUSY(STATUS)VALUES(STATUS_NAZWA);
END CREATE_STATUS;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_UMOWA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "BAZA"."CREATE_UMOWA" 
(
  UMOWA_POCZATEK IN DATE 
, UMOWA_KONIEC IN DATE 
, UMOWA_RODZAJ IN VARCHAR2 
, UMOWA_DODANO IN DATE 
) AS 
BEGIN
  INSERT INTO UMOWY (
  POCZATEK,
  KONIEC,
  RODZAJ,
  DODANO
  )VALUES(
  UMOWA_POCZATEK,
  UMOWA_KONIEC,
  UMOWA_RODZAJ,
  UMOWA_DODANO
  );
END CREATE_UMOWA;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_UMOWA0
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_UMOWA0" 
(
  UMOWA_POCZATEK IN DATE 
, UMOWA_KONIEC IN DATE 
, UMOWA_RODZAJ IN VARCHAR2 
, UMOWA_DODANO IN DATE 
, UMOWA_ID_OFERTY IN NUMBER
,	UMOWA_ID_KONTRAHENTA IN NUMBER
) AS 
BEGIN
  INSERT INTO UMOWY (
  POCZATEK,
  KONIEC,
  RODZAJ,
  DODANO,
  ID_OFERTY
,	ID_KONTRAHENTA
  )VALUES(
  UMOWA_POCZATEK,
  UMOWA_KONIEC,
  UMOWA_RODZAJ,
  UMOWA_DODANO,
  UMOWA_ID_OFERTY
,	UMOWA_ID_KONTRAHENTA
  );
END CREATE_UMOWA0;

/
--------------------------------------------------------
--  DDL for Procedure CREATE_UMOWA1
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."CREATE_UMOWA1" 
(
  UMOWA_POCZATEK IN DATE 
, UMOWA_KONIEC IN DATE 
, UMOWA_RODZAJ IN VARCHAR2 
, UMOWA_DODANO IN DATE 
, WYMIAR IN VARCHAR2
, STAWKA IN NUMBER
,	FIRMA IN VARCHAR2
,	STANOWISKO IN VARCHAR2
, NAZWISKO IN VARCHAR2
, IMIE IN VARCHAR2
, MIEJSCOWOSC IN VARCHAR2
, STATUS IN VARCHAR2
) AS 
BEGIN
  INSERT INTO UMOWY (
  POCZATEK,
  KONIEC,
  RODZAJ,
  DODANO,
  ID_OFERTY
,	ID_KONTRAHENTA
  )VALUES(
  UMOWA_POCZATEK,
  UMOWA_KONIEC,
  UMOWA_RODZAJ,
  UMOWA_DODANO,
  (SELECT o.ID_OFERTY FROM OFERTY o, STANOWISKA s, FIRMY f WHERE o.WYMIAR_PRACY=WYMIAR AND o.STAWKA_DZIEN=STAWKA AND f.NAZWA=FIRMA AND s.NAZWA=STANOWISKO)
,	(SELECT k.ID_KONTRAHENTA FROM KONTRAHENCI k, STATUSY s WHERE k.NAZWISKO=NAZWISKO AND k.IMIE=IMIE AND k.MIEJSCOWOSC=MIEJSCOWOSC AND s.STATUS=STATUS)
  );
END CREATE_UMOWA1;

/
--------------------------------------------------------
--  DDL for Procedure GET_FIRMAF
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."GET_FIRMAF" 
(
   P_ID IN OFERTY.ID_FIRMY%TYPE,
   ref_cur_io OUT SYS_REFCURSOR
)
AS
BEGIN
  open ref_cur_io for
  select NAZWA, MIEJSCOWOSC, ULICA, NR_BUDYNKU, NR_TEL from FIRMY where id_FIRMY=p_id;
END;

/
--------------------------------------------------------
--  DDL for Procedure GET_KONTRAHENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."GET_KONTRAHENT" 
(
   P_imie IN KONTRAHENCI.IMIE%TYPE,
   P_nazwisko IN KONTRAHENCI.NAZWISKO%TYPE,
   ref_cur_io OUT SYS_REFCURSOR
)
AS
BEGIN
  open ref_cur_io for
   SELECT IMIE, NAZWISKO, MIEJSCOWOSC, ulica, NR_BUDYNKU ,nr_tel
   FROM KONTRAHENCI
   WHERE NAZWISKO = P_nazwisko OR IMIE = P_imie OR IMIE = P_imie AND NAZWISKO = P_nazwisko;
END GET_KONTRAHENT;

/
--------------------------------------------------------
--  DDL for Procedure GET_OFERTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."GET_OFERTA" 
(
   P_firma IN FIRMY.NAZWA%TYPE,
   P_wymiar IN OFERTY.WYMIAR_PRACY%TYPE,
   ref_cur_io OUT SYS_REFCURSOR
)
AS
BEGIN
  open ref_cur_io for
  select f.NAZWA, o.wymiar_pracy, o.stawka_dzien, o.ilosc_ofert from oferty o, FIRMY f where o.WYMIAR_PRACY=p_wymiar OR f.NAZWA=P_firma OR f.NAZWA=P_firma AND o.WYMIAR_PRACY=p_wymiar;
END;

/
--------------------------------------------------------
--  DDL for Procedure SELECT_KONTRAHENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."SELECT_KONTRAHENT" (   
p_id IN KONTRAHENCI.ID_KONTRAHENTA%TYPE,  
p_kontrahent_display OUT SYS_REFCURSOR)  
IS  
BEGIN  
  OPEN p_kontrahent_display for SELECT IMIE, NAZWISKO, MIEJSCOWOSC FROM KONTRAHENCI WHERE ID_KONTRAHENTA=p_id;  
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_BIUROAGENCJI
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."UPDATE_BIUROAGENCJI" (
 BIURO_E_MAIL IN VARCHAR2
, BIURO_NR_TEL IN NUMBER
, BIURO_FAX IN NUMBER

, BIURO_MIEJSCOWOSC IN VARCHAR2 
, BIURO_ULICA IN VARCHAR2 
, BIURO_NR_BUDYNKU IN NUMBER 
)
AS
BEGIN
  UPDATE BIURAAGENCJI SET E_MAIL = BIURO_E_MAIL, NR_TEL = BIURO_NR_TEL, FAX = BIURO_FAX 
  WHERE  MIEJSCOWOSC = BIURO_MIEJSCOWOSC AND ULICA = BIURO_ULICA AND NR_BUDYNKU = BIURO_NR_BUDYNKU;
  COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_KONTRAHENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."UPDATE_KONTRAHENT" 
(
  KONTRAHENT_MIEJSCOWOSC IN VARCHAR2 
, KONTRAHENT_ULICA IN VARCHAR2 
, KONTRAHENT_NR_BUDYNKU IN NUMBER 
, KONTRAHENT_NR_LOKALU IN NUMBER 
, KONTRAHENT_KOD_POCZTOWY IN NUMBER 
, KONTRAHENT_POCZTA IN VARCHAR2 
, KONTRAHENT_WOJEWODZTWO IN VARCHAR2 
, KONTRAHENT_NIP IN NUMBER 
, KONTRAHENT_NR_KONTA IN VARCHAR2
, KONTRAHENT_E_MAIL IN VARCHAR2 
, KONTRAHENT_NR_TEL IN NUMBER 
, KONTRAHENT_CV IN VARCHAR2 
, KONTRAHENT_STATUS IN VARCHAR2
, KONTRAHENT_IMIE IN VARCHAR2
, KONTRAHENT_NAZWISKO IN VARCHAR2
, KONTRAHENT_PESEL IN NUMBER 
) AS 
BEGIN
  UPDATE KONTRAHENCI SET
  MIEJSCOWOSC	= KONTRAHENT_MIEJSCOWOSC,
  ULICA	= KONTRAHENT_ULICA,
  NR_BUDYNKU = KONTRAHENT_NR_BUDYNKU,
  NR_LOKALU = KONTRAHENT_NR_LOKALU,
  KOD_POCZTOWY = KONTRAHENT_KOD_POCZTOWY
, POCZTA = KONTRAHENT_POCZTA
,  WOJEWODZTWO = KONTRAHENT_WOJEWODZTWO
,  NIP = KONTRAHENT_NIP
,  NR_KONTA = KONTRAHENT_NR_KONTA
,  E_MAIL = KONTRAHENT_E_MAIL
,  NR_TEL = KONTRAHENT_NR_TEL
,  CV	= KONTRAHENT_CV
,  ID_STATUS = KONTRAHENT_STATUS
  WHERE ID_KONTRAHENTA=(SELECT ID_KONTRAHENTA FROM KONTRAHENCI where IMIE=KONTRAHENT_IMIE AND NAZWISKO=KONTRAHENT_NAZWISKO AND PESEL=KONTRAHENT_PESEL);
  COMMIT;
END UPDATE_KONTRAHENT;

/
--------------------------------------------------------
--  DDL for Procedure UPDATE_OFERTY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "BAZA"."UPDATE_OFERTY" (
  ILOSC_OFERTY IN NUMBER 
, OPIS_OFERTY IN VARCHAR2 
, FIRMA IN VARCHAR2 
, WYMIAR_OFERTY IN VARCHAR2
, STAWKA IN NUMBER
, ID_STANOWISKA IN NUMBER
) AS 
BEGIN
  UPDATE OFERTY o SET
  o.ILOSC_OFERT = ILOSC_OFERTY
, o.OPIS = OPIS_OFERTY
  WHERE
  o.ID_OFERTY=(
  SELECT o.ID_OFERTY FROM FIRMY f, OFERTY o WHERE f.NAZWA = FIRMA AND o.WYMIAR_PRACY = WYMIAR_OFERTY AND o.STAWKA_DZIEN=STAWKA AND o.ID_STANOWISKA=ID_STANOWISKA);
  COMMIT;
END UPDATE_OFERTY;

/
--------------------------------------------------------
--  DDL for Package Body CONTRACTS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "BAZA"."CONTRACTS" AS

PROCEDURE CREATE_UMOWA1 
(
  UMOWA_POCZATEK IN DATE 
, UMOWA_KONIEC IN DATE 
, UMOWA_RODZAJ IN VARCHAR2 
, UMOWA_DODANO IN DATE 
, WYMIAR IN VARCHAR2
, STAWKA IN NUMBER
,	FIRMA IN VARCHAR2
,	STANOWISKO IN VARCHAR2
, NAZWISKO IN VARCHAR2
, IMIE IN VARCHAR2
, MIEJSCOWOSC IN VARCHAR2
, STATUS IN VARCHAR2
) AS 
BEGIN
  INSERT INTO UMOWY (
  POCZATEK,
  KONIEC,
  RODZAJ,
  DODANO,
  ID_OFERTY
,	ID_KONTRAHENTA
  )VALUES(
  UMOWA_POCZATEK,
  UMOWA_KONIEC,
  UMOWA_RODZAJ,
  UMOWA_DODANO,
  (SELECT o.ID_OFERTY FROM OFERTY o, STANOWISKA s, FIRMY f WHERE o.WYMIAR_PRACY=WYMIAR AND o.STAWKA_DZIEN=STAWKA AND f.NAZWA=FIRMA AND s.NAZWA=STANOWISKO)
,	(SELECT k.ID_KONTRAHENTA FROM KONTRAHENCI k, STATUSY s WHERE k.NAZWISKO=NAZWISKO AND k.IMIE=IMIE AND k.MIEJSCOWOSC=MIEJSCOWOSC AND s.STATUS=STATUS)
  );
END CREATE_UMOWA1;

END CONTRACTS;

/
--------------------------------------------------------
--  DDL for Package Body OFERTS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "BAZA"."OFERTS" AS

PROCEDURE CREATE_OFERTA1 
(
  OFERTA_WYMIAR_PRACY IN VARCHAR2 
, OFERTA_STAWKA_DZIEN IN NUMBER 
, OFERTA_STAWKA_NOC IN NUMBER 
, OFERTA_STAWKA_ND_SW IN NUMBER 
, OFERTA_ILOSC_OFERT IN NUMBER 
, OFERTA_OPIS IN VARCHAR2 
, OFERTA_DODANO IN DATE
, STANOWISKO IN VARCHAR2
, NAZWA IN VARCHAR2
) AS 
BEGIN
  INSERT INTO OFERTY(
  WYMIAR_PRACY
,STAWKA_DZIEN
,STAWKA_NOC
,STAWKA_ND_SW
,ILOSC_OFERT
,OPIS
,DODANO
,ID_STANOWISKA
,ID_FIRMY
)VALUES(
OFERTA_WYMIAR_PRACY
,OFERTA_STAWKA_DZIEN
,OFERTA_STAWKA_NOC
,OFERTA_STAWKA_ND_SW
,OFERTA_ILOSC_OFERT
,OFERTA_OPIS
,OFERTA_DODANO
,(SELECT s.ID_STANOWISKA FROM STANOWISKA s WHERE s.NAZWA=STANOWISKO)
,(SELECT f.ID_FIRMY FROM FIRMY f WHERE f.NAZWA=NAZWA)
);
END CREATE_OFERTA1;

PROCEDURE UPDATE_OFERTY (
  ILOSC_OFERTY IN NUMBER 
, OPIS_OFERTY IN VARCHAR2 
, FIRMA IN VARCHAR2 
, WYMIAR_OFERTY IN VARCHAR2 
) AS 
BEGIN
  UPDATE OFERTY o SET
  o.ILOSC_OFERT = ILOSC_OFERTY
, o.OPIS = OPIS_OFERTY
  WHERE
  o.ID_FIRMY=(
  SELECT f.ID_FIRMY FROM FIRMY f, OFERTY o WHERE f.NAZWA = FIRMA AND o.WYMIAR_PRACY = WYMIAR_OFERTY);
  COMMIT;
END UPDATE_OFERTY;

END OFERTS;

/
--------------------------------------------------------
--  DDL for Package Body STATUSES
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "BAZA"."STATUSES" AS

PROCEDURE CREATE_STATUS 
(
  STATUS_NAZWA IN VARCHAR2 
) AS 
BEGIN
  INSERT INTO STATUSY(STATUS)VALUES(STATUS_NAZWA);
END CREATE_STATUS;

END STATUSES;

/
--------------------------------------------------------
--  DDL for Package CONTRACTS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "BAZA"."CONTRACTS" AS 

 PROCEDURE CREATE_UMOWA1 
(
  UMOWA_POCZATEK IN DATE 
, UMOWA_KONIEC IN DATE 
, UMOWA_RODZAJ IN VARCHAR2 
, UMOWA_DODANO IN DATE 
, WYMIAR IN VARCHAR2
, STAWKA IN NUMBER
,	FIRMA IN VARCHAR2
,	STANOWISKO IN VARCHAR2
, NAZWISKO IN VARCHAR2
, IMIE IN VARCHAR2
, MIEJSCOWOSC IN VARCHAR2
, STATUS IN VARCHAR2
);

END CONTRACTS;

/
--------------------------------------------------------
--  DDL for Package OFERTS
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "BAZA"."OFERTS" AS 

PROCEDURE CREATE_OFERTA1 
(
  OFERTA_WYMIAR_PRACY IN VARCHAR2 
, OFERTA_STAWKA_DZIEN IN NUMBER 
, OFERTA_STAWKA_NOC IN NUMBER 
, OFERTA_STAWKA_ND_SW IN NUMBER 
, OFERTA_ILOSC_OFERT IN NUMBER 
, OFERTA_OPIS IN VARCHAR2 
, OFERTA_DODANO IN DATE
, STANOWISKO IN VARCHAR2
, NAZWA IN VARCHAR2
);

PROCEDURE UPDATE_OFERTY (
  ILOSC_OFERTY IN NUMBER 
, OPIS_OFERTY IN VARCHAR2 
, FIRMA IN VARCHAR2 
, WYMIAR_OFERTY IN VARCHAR2 
);

END OFERTS;

/
--------------------------------------------------------
--  DDL for Package SHOW
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "BAZA"."SHOW" AS 

PROCEDURE GETFIRMY(p_id IN FIRMY.ID_FIRMY%TYPE, ref_cur_io OUT SYS_REFCURSOR);

END SHOW;

/
--------------------------------------------------------
--  DDL for Package STATUSES
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "BAZA"."STATUSES" AS 

  PROCEDURE CREATE_STATUS (
  STATUS_NAZWA IN VARCHAR2 );

END STATUSES;

/
--------------------------------------------------------
--  DDL for Function CONTRACTS_BETWEEN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "BAZA"."CONTRACTS_BETWEEN" (
  PODPISANO IN DATE
  ,  PODPISANO2 IN DATE 
) RETURN NUMBER
AS 

c_liczba number;

CURSOR c1
is
  SELECT count(u.ID_UMOWY) 
  FROM UMOWY u
  WHERE u.DODANO BETWEEN PODPISANO AND PODPISANO2;
  
BEGIN
  OPEN c1;
    FETCH c1 INTO c_liczba;
  CLOSE c1;
RETURN c_liczba;
END CONTRACTS_BETWEEN;

/
--------------------------------------------------------
--  DDL for Function CONTRACTS_FROM
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "BAZA"."CONTRACTS_FROM" (
  PODPISANO IN DATE 
) RETURN NUMBER
AS 

c_liczba number;

CURSOR c1
is
  SELECT count(u.ID_UMOWY) 
  FROM UMOWY u
  WHERE u.DODANO BETWEEN PODPISANO AND SYSDATE;
  
BEGIN
  OPEN c1;
    FETCH c1 INTO c_liczba;
  CLOSE c1;
RETURN c_liczba;
END CONTRACTS_FROM;

/
--------------------------------------------------------
--  Constraints for Table BIURAAGENCJI
--------------------------------------------------------

  ALTER TABLE "BAZA"."BIURAAGENCJI" MODIFY ("ID_BIURA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."BIURAAGENCJI" MODIFY ("MIEJSCOWOSC" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."BIURAAGENCJI" MODIFY ("ULICA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."BIURAAGENCJI" MODIFY ("NR_BUDYNKU" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."BIURAAGENCJI" MODIFY ("KOD_POCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."BIURAAGENCJI" MODIFY ("NR_TEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FIRMY
--------------------------------------------------------

  ALTER TABLE "BAZA"."FIRMY" MODIFY ("ID_FIRMY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."FIRMY" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."FIRMY" MODIFY ("MIEJSCOWOSC" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."FIRMY" MODIFY ("NR_BUDYNKU" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."FIRMY" MODIFY ("KOD_POCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."FIRMY" MODIFY ("NR_TEL" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."FIRMY" ADD CONSTRAINT "FIRMY_PK" PRIMARY KEY ("ID_FIRMY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KONTRAHENCI
--------------------------------------------------------

  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("ID_KONTRAHENTA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("PLEC" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("DATA_URODZENIA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("MIEJSCOWOSC" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("NR_BUDYNKU" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("KOD_POCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("NR_KONTA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("NR_TEL" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("CV" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" ADD CONSTRAINT "KONTRACHENCI_PK" PRIMARY KEY ("ID_KONTRAHENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("DODANO" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KONTRAHENCI" MODIFY ("PESEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KWALIFIKACJE
--------------------------------------------------------

  ALTER TABLE "BAZA"."KWALIFIKACJE" MODIFY ("ID_KWALIFIKACJI" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KWALIFIKACJE" ADD CONSTRAINT "KWALIFIKACJE_PK" PRIMARY KEY ("ID_KWALIFIKACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BAZA"."KWALIFIKACJE" MODIFY ("NAZWA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KWALIFIKACJE_KONTRAHENTOW
--------------------------------------------------------

  ALTER TABLE "BAZA"."KWALIFIKACJE_KONTRAHENTOW" MODIFY ("ID_KONTRAHENTA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."KWALIFIKACJE_KONTRAHENTOW" MODIFY ("ID_KWALIFIKACJI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFERTY
--------------------------------------------------------

  ALTER TABLE "BAZA"."OFERTY" MODIFY ("ID_OFERTY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."OFERTY" MODIFY ("WYMIAR_PRACY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."OFERTY" MODIFY ("STAWKA_DZIEN" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."OFERTY" MODIFY ("ILOSC_OFERT" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."OFERTY" MODIFY ("DODANO" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."OFERTY" ADD CONSTRAINT "OFERTY_PK" PRIMARY KEY ("ID_OFERTY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OFERTY_KWALIFIKACJE
--------------------------------------------------------

  ALTER TABLE "BAZA"."OFERTY_KWALIFIKACJE" MODIFY ("ID_OFERTY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."OFERTY_KWALIFIKACJE" MODIFY ("ID_KWALIFIKACJI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STANOWISKA
--------------------------------------------------------

  ALTER TABLE "BAZA"."STANOWISKA" MODIFY ("ID_STANOWISKA" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."STANOWISKA" ADD CONSTRAINT "STANOWISKA_PK" PRIMARY KEY ("ID_STANOWISKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BAZA"."STANOWISKA" MODIFY ("NAZWA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATUSY
--------------------------------------------------------

  ALTER TABLE "BAZA"."STATUSY" MODIFY ("ID_STATUSU" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."STATUSY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."STATUSY" ADD CONSTRAINT "STATUSY_PK" PRIMARY KEY ("ID_STATUSU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UMOWY
--------------------------------------------------------

  ALTER TABLE "BAZA"."UMOWY" MODIFY ("ID_UMOWY" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."UMOWY" ADD CONSTRAINT "UMOWY_PK" PRIMARY KEY ("ID_UMOWY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BAZA"."UMOWY" MODIFY ("DODANO" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."UMOWY" MODIFY ("POCZATEK" NOT NULL ENABLE);
  ALTER TABLE "BAZA"."UMOWY" MODIFY ("KONIEC" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FIRMY
--------------------------------------------------------

  ALTER TABLE "BAZA"."FIRMY" ADD CONSTRAINT "FK_FIRMY_STATUS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "BAZA"."STATUSY" ("ID_STATUSU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KONTRAHENCI
--------------------------------------------------------

  ALTER TABLE "BAZA"."KONTRAHENCI" ADD CONSTRAINT "FK_KONTRAHENCI_STATUS" FOREIGN KEY ("ID_STATUS")
	  REFERENCES "BAZA"."STATUSY" ("ID_STATUSU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KWALIFIKACJE_KONTRAHENTOW
--------------------------------------------------------

  ALTER TABLE "BAZA"."KWALIFIKACJE_KONTRAHENTOW" ADD CONSTRAINT "FK_KWA_KON_KONTRAHENCI" FOREIGN KEY ("ID_KONTRAHENTA")
	  REFERENCES "BAZA"."KONTRAHENCI" ("ID_KONTRAHENTA") ENABLE;
  ALTER TABLE "BAZA"."KWALIFIKACJE_KONTRAHENTOW" ADD CONSTRAINT "FK_KWA_KON_KWALIFIKACJE" FOREIGN KEY ("ID_KWALIFIKACJI")
	  REFERENCES "BAZA"."KWALIFIKACJE" ("ID_KWALIFIKACJI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFERTY
--------------------------------------------------------

  ALTER TABLE "BAZA"."OFERTY" ADD CONSTRAINT "FK_OFERTY_STANOWISK" FOREIGN KEY ("ID_STANOWISKA")
	  REFERENCES "BAZA"."STANOWISKA" ("ID_STANOWISKA") ENABLE;
  ALTER TABLE "BAZA"."OFERTY" ADD CONSTRAINT "FK_OFERTY_FIRMY" FOREIGN KEY ("ID_FIRMY")
	  REFERENCES "BAZA"."FIRMY" ("ID_FIRMY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OFERTY_KWALIFIKACJE
--------------------------------------------------------

  ALTER TABLE "BAZA"."OFERTY_KWALIFIKACJE" ADD CONSTRAINT "FK_OFER_KWA_OFERTY" FOREIGN KEY ("ID_OFERTY")
	  REFERENCES "BAZA"."OFERTY" ("ID_OFERTY") ENABLE;
  ALTER TABLE "BAZA"."OFERTY_KWALIFIKACJE" ADD CONSTRAINT "FK_OFER_KWA_KWALIFIKACJE" FOREIGN KEY ("ID_KWALIFIKACJI")
	  REFERENCES "BAZA"."KWALIFIKACJE" ("ID_KWALIFIKACJI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UMOWY
--------------------------------------------------------

  ALTER TABLE "BAZA"."UMOWY" ADD CONSTRAINT "FK_UMOWY_OFERTY" FOREIGN KEY ("ID_OFERTY")
	  REFERENCES "BAZA"."OFERTY" ("ID_OFERTY") ENABLE;
  ALTER TABLE "BAZA"."UMOWY" ADD CONSTRAINT "FK_UMOWY_KONTRAHENCI" FOREIGN KEY ("ID_KONTRAHENTA")
	  REFERENCES "BAZA"."KONTRAHENCI" ("ID_KONTRAHENTA") ENABLE;
